name: Daily RSS Feed Fetcher

on:
  schedule:
    - cron: '0 0 * * *'  # once daily at midnight UTC
  workflow_dispatch:  # allow manual trigger

jobs:
  fetch-daily-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Fetch and store RSS feed
        run: |
          python fetch_rss.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rss_feeds/*
          git commit -m "Add RSS feed for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
